#escreva um passo a passo para fazer um miojo, bom apetite
print("Pegar um miojo")
print("pegar uma panela.")
print("enxer a panela com agua.")
print("colocar a panela no fogão.")
print("liga a boca do fogão.")
print("esperar a agua ferver.")
print("com agua fervendo, abrir pacote do miojo.")
print("retirar o macarrao tipo miojo do pacote")
print("colocar o macarrao na agua fervendo dentro da panela")
print("esperar o cozimento por 3 minutos")
print("desligar o fogo, apos o cozimento")
print("acrescentar tempero no macarrao")
print("servir o macarrao em um prato")